version: "3.8"

services:
  yandex-rasp:
    container_name: yandex-rasp
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_URL: postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.4
    volumes:
      - ./docker/postgres/data:/data/postgres
      - ./src/main/resources/db/migration/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 10

networks:
  backend: