server:
  port: 8080

logging:
  level:
    root: info

spring:
  application:
    name: "yandex-rasp-kotlin"

  datasource:
    url: "jdbc:postgresql://${DB_URL}/yandex_rasp_db"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    driverClassName: "org.postgresql.Driver"

  jpa:
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
      query:
        in_clause_parameter_padding: true
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  graphql:
    schema:
      fileExtensions: ".graphqls,.gqls,.graphql"
    graphiql:
      enabled: true

app:
  feign:
    client:
      yandex:
        rasp:
          api-key: "${YANDEX_RASP_KEY}"
          url: "https://api.rasp.yandex.net/v3.0"
          connect-timeout: 5000
          read-timeout: 5000